### PR TITLE
added new favicons [RFR]

### PR DESCRIPTION
**Pull request by mandym-webdev**

### CODE REVIEW

**Comment by lifehackett** [comment]
I've never played with this stuff, but seems reasonable to me. 
1) I don't see the `browserconfig.xml` referenced anywhere so it doesn't look like the site is using it
2) You will need to update `gulpfile.js` to copy the files into the dist folder, otherwise they won't get served up.  Around line 40 you should see the gulp "copy" task with an example of how to copy over `index.html`.  Add entries in that same task for the 2 new files.  You don't need to worry about the favicons because they will get picked up by the existing copy task for images.

**Comment by mandym-webdev** [comment]
I updated the gulpfile.  It seems IE automatically searches for a 
browserconfig file in the root so it doesn't need to be called explicitly.

**Comment by lifehackett** [comment]
@mandym-webdev Can this be merged?

**Comment by mandym-webdev** [comment]
yes, it was just waiting for your ok

**Pull request merged**
