### PR TITLE
add GA to production only [RFR]

### PR DESCRIPTION
**Pull request by mandym-webdev**
I set it up so the GA only gets run in production by running a specific gulp command.  This is branched off of analytics so it should be merged to there before analytics is merged to master.

### CODE REVIEW

**Comment by lifehackett** [comment]
The `postinstall` script will need to be updated so when deployed to Heroku the GA code gets run

**Comment by mandym-webdev** [comment]
so would it then be:

"postinstall": "cd ./server && npm install && cd ../client && npm 
install && node_modules/.bin/gulp && gulp copy --production"

**Comment by mandym-webdev** [comment]
@lifehackett @Ortuna @seanperkins I pushed the change to the postinstall. Can one of you review it so we can wrap this up?  Thanks

**Comment by lifehackett** [comment]
@mandym-webdev The update looks good to me

**Pull request merged**
